- src/Connector.AzureDataLake/Connector/AzureDataLakeClient.cs
- src/Connector.AzureDataLake/Connector/AzureDataLakeConnector.cs
- src/Connector.AzureDataLake/Connector/IAzureDataLakeClient.cs
- test/integration/Connector.AzureDataLake.Tests.Integration/AzureDataLakeConnectorTests.cs
feat: Implement sync mode
Work Item ID: [AB#23755](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/23755)
> feat: Implement sync mode

- Directory.Build.props
- azure-pipelines.yml
- docs/4.0.0-release-notes.md
- global.json
- test/integration/Connector.AzureDataLake.Tests.Integration/Connector.AzureDataLake.Tests.Integration.csproj
- test/unit/Connector.AzureDataLake.Tests.Unit/Connector.AzureDataLake.Tests.Unit.csproj
Work Item ID: [AB#24172](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/24172)
> chore: Update to support .NET 6.0

- src/Connector.DataLake.Common/Connector/DataLakeConnector.cs
Work Item ID: [AB#37171](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/37171)
Manually in docker
> feat: ReQueue store data on any exception

- src/Connector.DataLake.Common/Connector/DataLakeConnector.cs
- src/Connector.DataLake.Common/Connector/DataLakeExportEntitiesJobBase.cs
- src/Connector.DataLake.Common/DataLakeConnectorComponentBase.cs
- src/Connector.DataLake.Common/DataLakeConstants.cs
Work Item ID: [AB#37419](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/37419)
Locally
> fix: Validate output format and schedule

- src/Connector.AzureDatabricks/AzureDatabricksConnectorJobData.cs
- src/Connector.AzureDatabricks/AzureDatabricksConnectorProvider.cs
- src/Connector.AzureDatabricks/AzureDatabricksConstants.cs
- src/Connector.AzureDatabricks/Connector/AzureDatabricksClient.cs
- src/Connector.SynapseDataEngineering/Connector/SynapseDataEngineeringClient.cs
- src/Connector.SynapseDataEngineering/SynapseDataEngineeringConnectorJobData.cs
- src/Connector.SynapseDataEngineering/SynapseDataEngineeringConnectorProvider.cs
- src/Connector.SynapseDataEngineering/SynapseDataEngineeringConstants.cs
Work Item ID: [AB#40044](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/40044)
Update Databricks and Data Engineering connector to be based on OneLake instead of ADLSG2
Local
> feat: Update databricks dataengineering based onelake

- docs/4.3.3-release-notes.md
- src/Connector.DataLake.Common/Connector/DataLakeExportEntitiesJobBase.cs
- src/Connector.DataLake.Common/DataLakeConnectorComponentBase.cs
- src/Connector.DataLake.Common/DataLakeJobArgs.cs
- src/Connector.DataLake.Common/DataLakeJobBase.cs
Work Item ID: [AB#40521](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/40521)
Local environment
- Prevent multiple files being written due to scheduler being triggered out of sync in multiple cluedin-server instances
> fix: Prevent multiple files per run

- docs/4.3.2-release-notes.md
- docs/4.3.3-release-notes.md
- docs/4.4.0-release-notes.md
- src/Connector.DataLake.Common/Connector/DataLakeExportEntitiesJobBase.cs
- src/Connector.DataLake.Common/DataLakeConnectorComponentBase.cs
- src/Connector.DataLake.Common/DataLakeJobArgs.cs
- src/Connector.DataLake.Common/DataLakeJobBase.cs
> chore: Merge release/4.3.3 into develop

- src/Connector.AzureAIStudio/Connector/AzureAIStudioConnector.cs
- src/Connector.AzureAIStudio/Connector/AzureAIStudioExportEntitiesJob.cs
- src/Connector.AzureDataLake/Connector/AzureDataLakeConnector.cs
- src/Connector.AzureDataLake/Connector/AzureDataLakeExportEntitiesJob.cs
- src/Connector.AzureDatabricks/Connector/AzureDatabricksConnector.cs
- src/Connector.AzureDatabricks/Connector/AzureDatabricksExportEntitiesJob.cs
- src/Connector.DataLake.Common/Connector/DataLakeClient.cs
- src/Connector.DataLake.Common/Connector/DataLakeConnector.cs
- src/Connector.DataLake.Common/Connector/DataLakeExportEntitiesJobBase.cs
- src/Connector.DataLake.Common/Connector/IDataLakeClient.cs
- src/Connector.OneLake/Connector/OneLakeConnector.cs
- src/Connector.OneLake/Connector/OneLakeExportEntitiesJob.cs
- src/Connector.SynapseDataEngineering/Connector/SynapseDataEngineeringConnector.cs
- src/Connector.SynapseDataEngineering/Connector/SynapseDataEngineeringExportEntitiesJob.cs
- test/integration/Connector.AzureDataLake.Tests.Integration/AzureDataLakeConnectorTests.cs
Work Item ID: [AB#40521](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/40521)
Local environment
Metadata are added to file during export to record StreamId and DataTime
> feat: Use file metadata to control whether to skip export

- docs/4.5.0-release-notes.md
- docs/guides/FilenamePatterns.md
- src/Connector.AzureAIStudio/Connector/AzureAIStudioExportEntitiesJob.cs
- src/Connector.AzureDatabricks/Connector/AzureDatabricksExportEntitiesJob.cs
- src/Connector.DataLake.Common/Connector/DataLakeExportEntitiesJobBase.cs
- src/Connector.DataLake.Common/DataLakeConstants.cs
- src/Connector.DataLake.Common/DataLakeJobData.cs
- src/Connector.DataLake.Common/IDataLakeJobData.cs
- src/Connector.OneLake/Connector/OneLakeExportEntitiesJob.cs
- src/Connector.SynapseDataEngineering/Connector/SynapseDataEngineeringExportEntitiesJob.cs
Allow setting of file name pattern for export file names
Work Item ID: AB#
Local environment
Allow setting of file name pattern for export file names
> feat: Filename pattern

- src/Connector.DataLake.Common/Buffer.cs
Work Item ID: [AB#41489](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/41489)
Local environment
> fix: Prevent overlapping flush from occurring causing exception when releasing semaphore

- src/Connector.DataLake.Common/DataLakeConnectorComponentBase.cs
Work Item ID: [AB#41267](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/41267)
Local environemnt
> fix: Prevent infinite loop spam when unfixable error happens during scheduling

- src/Connector.AzureAIStudio/AzureAIStudioConnectorComponent.cs
- src/Connector.AzureDataLake/AzureDataLakeConnectorComponent.cs
- src/Connector.AzureDatabricks/AzureDatabricksConnectorComponent.cs
- src/Connector.DataLake.Common/DataLakeConnectorComponentBase.cs
- src/Connector.DataLake.Common/DataMigrator.cs
- src/Connector.DataLake.Common/IDataMigrator.cs
- src/Connector.OneLake/OneLakeConnectorComponent.cs
- src/Connector.SynapseDataEngineering/SynapseDataEngineeringConnectorComponent.cs
Work Item ID: AB#415280 [AB#42313](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/42313)
Key is settings table is limited to only 50 characters
Manually using local environment
> fix: Use short keys to prevent key truncation

- dic/en-US_User.dic
- src/Connector.AzureAIStudio/Connector/AzureAIStudioExportEntitiesJob.cs
- src/Connector.AzureDatabricks/Connector/AzureDatabricksExportEntitiesJob.cs
- src/Connector.DataLake.Common/Connector/DataLakeConnector.cs
- src/Connector.DataLake.Common/Connector/DataLakeExportEntitiesJobBase.cs
- src/Connector.DataLake.Common/Connector/SqlDataWriter/ISqlDataWriter.cs
- src/Connector.DataLake.Common/Connector/SqlDataWriter/SqlDataWriterBase.cs
- src/Connector.DataLake.Common/Connector/SqlExceptionExtensions.cs
- src/Connector.DataLake.Common/CronSchedules.cs
- src/Connector.DataLake.Common/DataLakeConnectorComponentBase.cs
- src/Connector.DataLake.Common/DataLakeConstants.cs
- src/Connector.DataLake.Common/DataLakeJobArgs.cs
- src/Connector.DataLake.Common/DataLakeJobBase.cs
- src/Connector.DataLake.Common/DataLakeScheduler.cs
- src/Connector.DataLake.Common/EventHandlers/RemoveStreamEventHandler.cs
- src/Connector.DataLake.Common/EventHandlers/UpdateExportTargetEventHandler.cs
- src/Connector.DataLake.Common/EventHandlers/UpdateStreamEventHandler.cs
- src/Connector.DataLake.Common/EventHandlers/UpdateStreamScheduleBase.cs
- src/Connector.DataLake.Common/IDataLakeConstants.cs
- src/Connector.DataLake.Common/IDataLakeJobArgs.cs
- src/Connector.DataLake.Common/IScheduledJobQueue.cs
- src/Connector.DataLake.Common/IScheduler.cs
- src/Connector.DataLake.Common/QueuedJob.cs
- src/Connector.DataLake.Common/Scheduler.cs
- src/Connector.DataLake.Common/StreamsHelper.cs
- src/Connector.OneLake/Connector/OneLakeExportEntitiesJob.cs
- src/Connector.SynapseDataEngineering/Connector/SynapseDataEngineeringExportEntitiesJob.cs
- test/integration/Connector.AzureDataLake.Tests.Integration/AzureDataLakeConnectorTests.cs
Work Item ID: [AB#41655](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/41655)
Ability to check for missed export. Saves export history in StreamCache_{STreamId}_ExportHistory table
Change scheduler to work using DateTimeOffset instead of DateTime during refactoring, in anticipation of custom cron that allows for timezone selection
Manually in local environment
Ability to check for missed export
> feat: Recover from missed export

- src/Connector.DataLake.Common/Connector/DataLakeConnector.cs
Work Item ID: [AB#43217](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/43217)
Locally, Manually
> fix: Do not validate stream cache related options when stream cache is disabled

- Packages.props
- docs/4.5.0-release-notes.md
- src/Connector.AzureDataLake/AzureDataLakeConstants.cs
- src/Connector.OneLake/OneLakeConstants.cs
Work Item ID: [AB#43442](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/43442)
Work Item ID: [AB#43440](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/43440)
Manually in local
> feat: Disallow spaces in configuration field

- docs/4.4.1-release-notes.md
Work Item ID: [AB#44595](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/44595)
- Add option to enable or disable escaping of non a-z,A-Z,0-9,_ characters
- Add option to enable or disable writing of guids as strings
> doc: Add release notes

- build/integration-test.ps1
Work Item ID:[AB#45435](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/45435)
> fix: Add encrypt false to connection string

- src/Connector.DataLake.Common/Connector/DataLakeClient.cs
- src/Connector.DataLake.Common/Connector/DataLakeConnector.cs
- src/Connector.DataLake.Common/Connector/IDataLakeClient.cs
- src/Connector.DataLake.Common/DataLakeContainer.cs
- test/integration/Connector.AzureDataLake.Tests.Integration/AzureDataLakeConnectorTests.cs
Work Item ID: https://dev.azure.com/CluedIn-io/CluedIn/_workitems/edit/47313
Related PR: https://github.com/CluedIn-io/Azure-Extensions/pull/341
Locally with Docker
> Add Implementation of GetContainers

- CluedIn.Connector.AzureDataLake.sln
- README.md
- azure-pipelines.yml
- build/integration-test.ps1
- docs/4.4.4-release-notes.md
- src/Connector.AzureDataLake/AzureDataLakeConstants.cs
- src/Connector.DataLake.Common/Connector/DataLakeClient.cs
- src/Connector.DataLake.Common/Connector/DataLakeConnector.cs
- src/Connector.DataLake.Common/Connector/DataLakeExportEntitiesJobBase.cs
- src/Connector.DataLake.Common/Connector/IDataLakeClient.cs
- src/Connector.DataLake.Common/Connector/SqlDataWriter/CsvSqlDataWriter.cs
- src/Connector.DataLake.Common/Connector/SqlDataWriter/ParquetSqlDataWriter.cs
- src/Connector.DataLake.Common/Connector/SqlDataWriter/SqlDataWriterBase.cs
- src/Connector.DataLake.Common/ConnectorProviderBase.cs
- src/Connector.DataLake.Common/DataLakeConnectorComponentBase.cs
- src/Connector.DataLake.Common/DataLakeConstants.cs
- src/Connector.DataLake.Common/DataLakeExtendedConfigurationProvider.cs
- src/Connector.DataLake.Common/DataLakeJobData.cs
- src/Connector.DataLake.Common/EventHandlers/RemoteEventExtensions.cs
- src/Connector.DataLake.Common/EventHandlers/RemoveStreamEventHandler.cs
- src/Connector.DataLake.Common/EventHandlers/UpdateExportTargetEventHandler.cs
- src/Connector.DataLake.Common/EventHandlers/UpdateStreamScheduleBase.cs
- src/Connector.DataLake.Common/IDataLakeJobData.cs
- src/Connector.DataLake.Common/Properties/AssemblyInfo.cs
- src/Connector.OneLake/Connector/OneLakeClient.cs
- src/Connector.OneLake/Connector/OneLakeConnector.cs
- src/Connector.OneLake/Connector/OneLakeExportEntitiesJob.cs
- src/Connector.OneLake/OneLakeConnectorJobData.cs
- src/Connector.OneLake/OneLakeConstants.cs
- test/integration/Connector.AzureDataLake.Tests.Integration/AzureDataLakeConnectorTests.cs
Work Item ID: AB#
One lake improvements based off open mirroring branch
Locally , manually
Added ability to load data to Lakehouse table after exporting in OneLake connector
> Cherry pick for 4.4.4 based off open mirroring branch

- azure-pipelines.yml
- src/Connector.OneLake/OneLakeConnectorJobData.cs
> fix: Prevent exception when using event stream mode

- src/Connector.AzureDataLake/AzureDataLakeConstants.cs
- src/Connector.OneLake/Connector/OneLakeConnector.cs
- src/Connector.OneLake/OneLakeConnectorJobData.cs
- src/Connector.OneLake/OneLakeConstants.cs
Work Item ID: [AB#48138](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/48138)
Expose Escape Vocabulary Key and Write array columns settings
> fix: Expose setting

- CluedIn.Connector.AzureDataLake.sln
- Directory.Build.props
- src/Connector.DataLake.Common/DataLakeConstants.cs
- src/Connector.DataLake.Common/DataLakeJobData.cs
- src/Connector.FabricOpenMirroring/Connector.FabricOpenMirroring.csproj
- src/Connector.FabricOpenMirroring/Connector/OpenMirroringClient.cs
- src/Connector.FabricOpenMirroring/Connector/OpenMirroringConnector.cs
- src/Connector.FabricOpenMirroring/Connector/OpenMirroringExportEntitiesJob.cs
- src/Connector.FabricOpenMirroring/Connector/SqlDataWriter/OpenMirroringParquetSqlDataWriter.cs
- src/Connector.FabricOpenMirroring/EventHandlers/ExportTargetEventHandler.cs
- src/Connector.FabricOpenMirroring/IOpenMirroringConstants.cs
- src/Connector.FabricOpenMirroring/InstallComponents.cs
- src/Connector.FabricOpenMirroring/OpenMirroringConnectorComponent.cs
- src/Connector.FabricOpenMirroring/OpenMirroringConnectorJobData.cs
- src/Connector.FabricOpenMirroring/OpenMirroringConnectorProvider.cs
- src/Connector.FabricOpenMirroring/OpenMirroringConstants.cs
- src/Connector.FabricOpenMirroring/OpenMirroringJobDataFactory.cs
- src/Connector.FabricOpenMirroring/Resources/fabricOpenMirroring.svg
Work Item ID: AB#
Open Mirroring Connector
> feat: Open Mirroring

- docs/4.4.4-release-notes.md
> doc: Update release notes

- src/Connector.DataLake.Common/Connector/DataLakeExportEntitiesJobBase.cs
- src/Connector.FabricOpenMirroring/Connector/OpenMirroringConnector.cs
- src/Connector.FabricOpenMirroring/Connector/SqlDataWriter/OpenMirroringParquetSqlDataWriter.cs
Merge release/4.4.4 into develop
> fix: row marker not exported (#102)

- docs/4.4.6-release-notes.md
- src/Connector.DataLake.Common/Connector/DataLakeExportEntitiesJobBase.cs
- src/Connector.FabricOpenMirroring/Connector/OpenMirroringExportEntitiesJob.cs
Work Item ID: [AB#49244](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/49244)
Add _partnerEvents.json when exporting to Open Mirroring for telemetry
> feat: Add _partnerEvents.json when exporting to Open Mirroring

- src/Connector.DataLake.Common/Connector/DataLakeExportEntitiesJobBase.cs
- src/Connector.DataLake.Common/Connector/SqlDataWriter/CsvSqlDataWriter.cs
- src/Connector.DataLake.Common/Connector/SqlDataWriter/SqlDataWriterBase.cs
- src/Connector.FabricOpenMirroring/Connector/OpenMirroringExportEntitiesJob.cs
- src/Connector.FabricOpenMirroring/Connector/SqlDataWriter/OpenMirroringCsvSqlDataWriter.cs
- src/Connector.FabricOpenMirroring/Connector/SqlDataWriter/OpenMirroringParquetSqlDataWriter.cs
- src/Connector.FabricOpenMirroring/Connector/SqlDataWriter/ValueHelper.cs
- src/Connector.FabricOpenMirroring/OpenMirroringConstants.cs
Work Item ID: [AB#49324](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/49324) [AB#49365](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/49365)
Row Marker only for second file onwards
Fix row marker output for CSV
> fix: Fix row marker for Open Mirroring output

- docs/4.4.5-release-notes.md
- docs/4.4.6-release-notes.md
- docs/4.5.1-release-notes.md
- src/Connector.DataLake.Common/Connector/DataLakeConnector.cs
- src/Connector.DataLake.Common/Connector/DataLakeExportEntitiesJobBase.cs
- src/Connector.DataLake.Common/Connector/SqlDataWriter/CsvSqlDataWriter.cs
- src/Connector.DataLake.Common/Connector/SqlDataWriter/ISqlDataWriter.cs
- src/Connector.DataLake.Common/Connector/SqlDataWriter/JsonSqlDataWriter.cs
- src/Connector.DataLake.Common/Connector/SqlDataWriter/ParquetSqlDataWriter.cs
- src/Connector.DataLake.Common/Connector/SqlDataWriter/SqlDataWriterBase.cs
- src/Connector.FabricOpenMirroring/Connector/OpenMirroringExportEntitiesJob.cs
- src/Connector.FabricOpenMirroring/Connector/SqlDataWriter/OpenMirroringCsvSqlDataWriter.cs
- src/Connector.FabricOpenMirroring/Connector/SqlDataWriter/OpenMirroringParquetSqlDataWriter.cs
- src/Connector.FabricOpenMirroring/Connector/SqlDataWriter/ValueHelper.cs
- src/Connector.FabricOpenMirroring/OpenMirroringConstants.cs
- test/unit/Connector.AzureDataLake.Tests.Unit/BufferTests.cs
> chore: release/4.5.1

- .editorconfig
- src/Connector.AzureDataLake/Connector/AzureDataLakeConnector.cs
- src/Connector.DataLake.Common/Connector/DataLakeClient.cs
- src/Connector.DataLake.Common/Connector/DataLakeConnector.cs
- src/Connector.FabricOpenMirroring/Connector/OpenMirroringClient.cs
- src/Connector.FabricOpenMirroring/Connector/OpenMirroringConnector.cs
- src/Connector.OneLake/Connector/OneLakeConnector.cs
- test/integration/Connector.AzureDataLake.Tests.Integration/AzureDataLakeConnectorTests.cs
- test/integration/Connector.FabricOpenMirroring.Tests.Integration/FabricOpenMirroringConnectorTests.cs
- test/integration/Connector.OneLake.Tests.Integration/OneLakeConnectorTests.cs
Work Item ID: [AB#49247](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/49247) [AB#48818](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/48818) [AB#48720](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/48720) [AB#48978](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/48978) [AB#49528](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/49528) [AB#49270](https://dev.azure.com/CluedIn-io/c054b4ae-1dab-43c2-af97-3683c744782f/_workitems/edit/49270)
Better error messages when verifying connection
> fix: Provide better error messages when verifying connection
